### ISSUE TITLE
Update paths in marketplace basic CFT

### ISSUE THREAD

**Issue by roncewind** [Senzing/aws-marketplace-evaluation#32]
There are a couple specified paths that need to be updated in the basic CFT:

cloudformation-senzing-basic.yaml
```  
ListenerPort443:
...
          RedirectConfig:
            Host: hub.senzing.com
            Path: /aws-cloudformation-ecs-senzing-stack-basic/
            Port: '443'
            Protocol: HTTPS
```

```
              <p>
                  For more information on the
                  <a href="https://github.com/Senzing/aws-cloudformation-ecs-senzing-stack-basic">Senzing basic components</a>
```
